CREATE TABLE IF NOT EXISTS users (
	uid CHARACTER VARYING(8) PRIMARY KEY,
	login CHARACTER VARYING(30) UNIQUE NOT NULL,
	pass CHARACTER VARYING(128) NOT NULL,
	session_key CHARACTER VARYING(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS calendars (
	uid CHARACTER VARYING(8) PRIMARY KEY,
	name CHARACTER VARYING(30) NOT NULL,
	owner CHARACTER VARYING(8) REFERENCES users(uid),
	accessible BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS events (
	uid CHARACTER VARYING(8) PRIMARY KEY,
	name CHARACTER VARYING(30) NOT NULL,
	"desc" CHARACTER VARYING(300),
	owner CHARACTER VARYING(8) REFERENCES users(uid),
	calendar CHARACTER VARYING(8) REFERENCES calendars(uid),
	date DATE DEFAULT '1990-01-01'
);
